name: CI Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-build-ubuntu:
    name: Build Check (Ubuntu / Debian)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev

      - name: Compile
        run: make

  test-build-fedora:
    name: Build Check (Fedora)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install git
        run: dnf install -y git

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Install dependencies
        run: |
          dnf install -y gcc make ncurses-devel

      - name: Compile
        run: make

  test-build-windows:
    name: Build Check (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup MSYS2 and toolchain
        uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884 # v2.32.0
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-pdcurses

      - name: Compile
        shell: msys2 {0}
        run: |
          mingw32-make
